### ISSUE TITLE
プライバシーポリシー記載のメールアドレスの修正

### ISSUE THREAD

**Issue by koyamaps** [Yoki-Inc/yoki.inc#1]
# 概要
日本語版ページに記載のプライバシーポリシーのメールアドレスに修正が必要。

# 目的
ウェブサイトのドメインが yoki-jp.com から yoki.inc に変更されたことに伴いメールアドレスの変更もされましたが、変更がされていません。

# タスク
- [ ] `/yoki.inc/ja/privacy_policy.html` の116行目 `COO@yoki-jp.com` を `COO@yoki.inc` に修正
- [ ] `/yoki.inc/ja/privacy_policy.html` の117行目と118行目の間に改定日を追加
- [ ] Internal用のリーガル資料の修正

**Comment by naonosuke** [comment]
こちらについては legal.yoki-jp.com へのリンクへ変更で対応します。また、規約自体の修正はマスターレポジトリ（ https://github.com/Yoki-Inc/legal ）でPRを開いてください。ありがとうございます。
